name: nutc_parking_info
version: 0.0.2+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  home_widget: ^0.1.6
  workmanager: ^0.5.1
  dio: ^4.0.6
  url_launcher: ^6.1.6

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

